development:
  env: "Dev"
  twitter:
    consumer_key: 'lu80N8gepFH2Q1KdhjwD2w'
    consumer_secret: 'Ut4V7XIHumlMulIgBvvrY4KQUHAezbaK5akB2bMKM9o'
    access_key: '206880109-A4CjhVr7Gj1FuXAghyluyLP8cb5we6bTcfFYhNIL'
    access_secret: 'IS10qU2oH9E7nSv6NDQgmOmFsntlYIwTPDmTOEBTY'
    
test:
  env: "Test"
  twitter:
    consumer_key: ''
    consumer_secret: ''
    access_key: ''
    access_secret: ''  

production:
  env: "Prod"
  twitter:
    consumer_key: 'lu80N8gepFH2Q1KdhjwD2w'
    consumer_secret: 'Ut4V7XIHumlMulIgBvvrY4KQUHAezbaK5akB2bMKM9o'
    access_key: '206880109-A4CjhVr7Gj1FuXAghyluyLP8cb5we6bTcfFYhNIL'
    access_secret: 'IS10qU2oH9E7nSv6NDQgmOmFsntlYIwTPDmTOEBTY'