development:
  bucket: champak_development
  access_key_id: AKIAI5JXGNLUZOHMAC6Q
  secret_access_key: 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

test:
  bucket: champak_test
  access_key_id: AKIAI5JXGNLUZOHMAC6Q
  secret_access_key: 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

production:
  bucket: champak_production
  access_key_id: AKIAI5JXGNLUZOHMAC6Q
  secret_access_key: 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
